### ISSUE TITLE
Instalacja pluginów z poziomu ACP

### ISSUE THREAD

**Issue by dedito** [linuxmintpl/mybb-theme#1]
Miała być zaimplementowana taka funkcjonalność, ale chyba została usunięta.

**Comment by Ulvhedin** [comment]
Własnie sie zastanawiam czy puścić na żywioł możliwośc instalacji pluginów. Tak naprawde pluginy instaluje sie raz i już. Dodatkowo, wiele pluginów nie ma spolszczenia - wymaga to manualnej interwencji. 
W chwili obecnej wszystko z repo mybb-plugin jest kopiowane ręcznie. Chwilowo tak zostawmy.

**Comment by dedito** [comment]
Ok, chyba wystarczająca jest instalacja poprzez repozytorium.
To zamykam i przesuwam do porzuconych.
