### ISSUE TITLE
Napisy nie mieszczą się w tabeli

### ISSUE THREAD

**Issue by Ulvhedin** [linuxmintpl/mybb-theme#4]
Napisy nie mieszczą się w tabeli w domyslnym stylu.
![Jak na załączonym obrazku](https://imgur.com/vAToEzUl.png)

**Comment by ciastek1981** [comment]
Przypuszczam, że popsuło się przez ten dodatek [Last poster avatar](https://community.mybb.com/mods.php?action=view&pid=74) .

Dobra Miętusy, **rozwiązanie problemu** jest gdzieś tu

https://community.mybb.com/thread-189492-page-8.html

**Za sugestią** stąd https://community.mybb.com/thread-218395-post-1307844.html#pid1307844

**Comment by Ulvhedin** [comment]
Wyglada na to ze funkcja obcinajaca tytuł robi 25 znakowy ciąg. Wydłużyłem pole o dodatkowe 30 px w szablonie: **forumbit_depth1_cat**
`<td class="tcat" width="230" align="center"><span class="smalltext"><strong>{$lang->forumbit_lastpost}</strong></span></td>`

Zerknijcie czy to jest OK, na szybki fix taki.

**Comment by dedito** [comment]
U mnie jest ok.

**Comment by dedito** [comment]
Brak uwag, wnioskuję, że wszystko ok. Zamykam.
