### ISSUE TITLE
W stylu Mint-light i Mint, tekst pola 'ostatni post' wchodzi na następne pole i nie wyglada to profesjonalnie przy węższej przeglądarce

### ISSUE THREAD

**Issue by Pavvlik** [linuxmintpl/mybb-theme#9]

**Comment by dedito** [comment]
Już to poprawiałem. Na jakim urządzeniu i przeglądarce jest ten błąd?

**Comment by yahoob3** [comment]
Na prod jest ok. "Bląd" został tylko na teście.

**Comment by dedito** [comment]
Ok sprawdziłem sobie zmniejszając okno i jest ten błąd w wynikach wyszukiwarki.
Generalnie chodzi o brak responsywności stylu.

**Comment by dedito** [comment]
Styl mint poprawiony.
Styl light prawdopodobnie przejmie i przerobi po swojemu yb3, ja w każdym razie nie mam nic przeciwko,
Na stylu mint mam jeszcze problem z różowym tłem w polu odpowiedzi, tam gdzie jest imagur. Na testowym nie mam tego efektu, a na produkcyjnym jest. Nie za bardzo wiem o co chodzi. Spróbuję przerzucić cały styl przez xml.

**Comment by dedito** [comment]
Style poprawione.
